/**
 * Andhra Pradesh Location Constants
 * Single source of truth for all state, district, and constituency data
 */

export const STATES = ['Andhra Pradesh'] as const;

export const ANDHRA_PRADESH_DISTRICTS = [
    "Alluri Sitharama Raju",
    "Anakapalli",
    "Anantapur",
    "Annamayya",
    "Bapatla",
    "Chittoor",
    "Dr. B. R. Ambedkar Konaseema",
    "East Godavari",
    "Eluru",
    "Guntur",
    "Kakinada",
    "Krishna",
    "Kurnool",
    "Nandyal",
    "NTR",
    "Palnadu",
    "Parvathipuram Manyam",
    "Prakasam",
    "Sri Potti Sriramulu Nellore",
    "Sri Sathya Sai",
    "Srikakulam",
    "Tirupati",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR Kadapa"
] as const;

export const ANDHRA_PRADESH_CONSTITUENCIES = [
    "Achanta",
    "Addanki",
    "Adoni",
    "Alamuru",
    "Allagadda",
    "Alur",
    "Amadalavalasa",
    "Amalapuram",
    "Anakapalli",
    "Anantapur Urban",
    "Anantapur Rural",
    "Anaparthy",
    "Araku Valley",
    "Atmakur",
    "Avanigadda",
    "Bapatla",
    "Bhimavaram",
    "Bhimili",
    "Bobbili",
    "Chandragiri",
    "Cheepurupalli",
    "Chilakaluripet",
    "Chintalapudi",
    "Chirala",
    "Chittoor",
    "Chodavaram",
    "Darsi",
    "Denduluru",
    "Dharmavaram",
    "Dhone",
    "Elamanchili",
    "Eluru",
    "Etcherla",
    "Gajapathinagaram",
    "Gannavaram",
    "Giddalur",
    "Gopalapuram",
    "Gudivada",
    "Gudur",
    "Guntakal",
    "Guntur East",
    "Guntur West",
    "Gurazala",
    "Hindupur",
    "Ichchapuram",
    "Jaggampeta",
    "Jaggayyapeta",
    "Jammalamadugu",
    "Kadapa",
    "Kadiri",
    "Kaikalur",
    "Kakinada City",
    "Kakinada Rural",
    "Kandukur",
    "Kanigiri",
    "Kavali",
    "Kodumur",
    "Kodur",
    "Kondapi",
    "Kothapeta",
    "Kovur",
    "Kovvur",
    "Kuppam",
    "Kurnool",
    "Kurupam",
    "Macherla",
    "Machilipatnam",
    "Madanapalle",
    "Mandapeta",
    "Markapuram",
    "Mangalagiri",
    "Medakonduru",
    "Mummidivaram",
    "Mydukur",
    "Nagari",
    "Nandyal",
    "Narasannapeta",
    "Narasapuram",
    "Narasaraopet",
    "Nellimarla",
    "Nellore City",
    "Nellore Rural",
    "Nidadavole",
    "Nuzvid",
    "Ongole",
    "Paderu",
    "Palakonda",
    "Palasa",
    "Palnadu",
    "Pamarru",
    "Parvathipuram",
    "Pathapatnam",
    "Payakaraopet",
    "Pedakurapadu",
    "Pedana",
    "Penamaluru",
    "Penukonda",
    "Pithapuram",
    "Polavaram",
    "Ponnur",
    "Prathipadu",
    "Proddatur",
    "Pulivendula",
    "Punganur",
    "Puthalapattu",
    "Pydibhimavaram",
    "Rajahmundry City",
    "Rajahmundry Rural",
    "Rajampet",
    "Rajanagaram",
    "Ramachandrapuram",
    "Ramagundam",
    "Rampachodavaram",
    "Rayachoti",
    "Rayadurg",
    "Razole",
    "Repalle",
    "Salur",
    "Santhanuthalapadu",
    "Sarvepalli",
    "Sattenapalli",
    "Singarayakonda",
    "Srikakulam",
    "Srisailam",
    "Srungavarapukota",
    "Sullurpeta",
    "Tadepalli",
    "Tadepalligudem",
    "Tadikonda",
    "Tanuku",
    "Tenali",
    "Thamballapalle",
    "Tirupati",
    "Tuni",
    "Udayagiri",
    "Unguturu",
    "Uravakonda",
    "Vemuru",
    "Venkatagiri",
    "Vijayawada Central",
    "Vijayawada East",
    "Vijayawada West",
    "Vinukonda",
    "Visakhapatnam East",
    "Visakhapatnam North",
    "Visakhapatnam South",
    "Visakhapatnam West",
    "Vizianagaram",
    "Yemmiganur",
    "Yerragondapalem",
    "Yuvathapalli"
] as const;

// Type exports for TypeScript
export type State = typeof STATES[number];
export type District = typeof ANDHRA_PRADESH_DISTRICTS[number];
export type Constituency = typeof ANDHRA_PRADESH_CONSTITUENCIES[number];
